### PR TITLE
feat: all caps file name

### PR DESCRIPTION
**Pull request by RakerZh**
All-caps file name can be used in cpp macros like this,`#ifndef PROJECT_TEST_H`

Also fix typo

### CODE REVIEW

**Comment by glepnir** [comment]
can we use a clearly name not `FILE_NAME` ?

**Comment by RakerZh** [comment]
how about `upper_file`

**Comment by glepnir** [comment]
or use `_expr:expand:param:%r:t` then we can do `vim.fn['expand'](param)`

**Comment by glepnir** [comment]
> how about `upper_file`

it's okay.

**Pull request merged**
